version: 3.7;
services:
  nginx:
    build: './.docker/nginx'
    ports:
      - '80:80'
    volumes:
      - './.docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './.public:/app/public'
    depends_on:
      - app

  app:
    build: './.docker/php'
    working_dir: '/app'
    volumes:
      - '.:/app'
      - './.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
    depends_on:
      - mysql
    environment:
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=password
      - AWS_URL=http://minio:9000
      - AWS_UPLOAD_BUCKET=uploads
      - AWS_S3_PATH_STYLE_ENDPOINT=true

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - './storage/mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}

  redis:
    image: redis:6.0-alpine
    ports:
      - '6379:6379'
